export const cardsData = [
    {
        id: 1,
        image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=500&h=500&fit=crop&crop=center",
        title: "Nutrition",
        duration: "12/90",
        unit: "weekly",
        description: "A plant-predominant, whole food diet helps prevent and manage chronic diseases effectively.",
    },
    {
        id: 2,
        image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop&crop=center",
        title: "Physical activity",
        duration: "32",
        unit: "minutes",
        description: "Engaging in regular movement supports cardiovascular health and enhances overall fitness.",
    },
    {
        id: 3,
        image: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=500&h=500&fit=crop&crop=center",
        title: "Restorative sleep",
        duration: "8",
        unit: "hours",
        description: "Quality sleep is foundational to mental clarity, emotional regulation, and physical repair.",
    },
    {
        id: 4,
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&h=500&fit=crop&crop=center",
        title: "Stress management",
        duration: "15",
        unit: "minutes",
        description: "Mindfulness, journaling, and breathing practices are effective tools for managing daily stress.",
    },
    {
        id: 5,
        image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=500&h=500&fit=crop&crop=center",
        title: "Social connection",
        duration: "1",
        unit: "interaction/day",
        description: "Maintaining meaningful relationships helps reduce anxiety and promotes emotional balance.",
    },
    {
        id: 6,
        image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=500&h=500&fit=crop&crop=center",
        title: "Substance abuse",
        duration: "0",
        unit: "instances",
        description: "Avoiding tobacco, alcohol, and recreational drugs supports long-term health and well-being.",
    },
    {
        id: 7,
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=500&fit=crop&crop=center",
        title: "Nutrition",
        duration: "3",
        unit: "balanced meals/day",
        description: "Balanced meals rich in fiber, healthy fats, and lean proteins promote energy and satiety.",
    },
    {
        id: 8,
        image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&h=500&fit=crop&crop=center",
        title: "Physical activity",
        duration: "150",
        unit: "minutes/week",
        description: "A mix of aerobic and strength exercises helps build endurance and support mobility.",
    },
    {
        id: 9,
        image: "https://images.unsplash.com/photo-1520206183501-b80df61043c2?w=500&h=500&fit=crop&crop=center",
        title: "Restorative sleep",
        duration: "7–9",
        unit: "hours/night",
        description: "Maintaining a consistent sleep routine supports hormone regulation and immune function.",
    },
    {
        id: 10,
        image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&h=500&fit=crop&crop=center",
        title: "Stress management",
        duration: "10",
        unit: "minutes/day",
        description: "Daily breathing techniques help activate the relaxation response and reduce tension.",
    },
    {
        id: 11,
        image: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=500&h=500&fit=crop&crop=center",
        title: "Social connection",
        duration: "2",
        unit: "conversations/day",
        description: "Regular positive interactions improve mood and create a buffer against life's challenges.",
    },
    {
        id: 12,
        image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&h=500&fit=crop&crop=center",
        title: "Substance abuse",
        duration: "0",
        unit: "alcohol units",
        description: "Minimizing alcohol intake supports liver health, better sleep, and cognitive performance.",
    },
    {
        id: 13,
        image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&h=500&fit=crop&crop=center",
        title: "Nutrition",
        duration: "5",
        unit: "servings of vegetables",
        description: "Eating a variety of colorful vegetables supports gut health and lowers inflammation.",
    },
    {
        id: 14,
        image: "https://images.unsplash.com/photo-1502904550040-7534597429ae?w=500&h=500&fit=crop&crop=center",
        title: "Physical activity",
        duration: "10,000",
        unit: "steps/day",
        description: "Daily walking improves cardiovascular endurance and reduces sedentary behavior.",
    },
    {
        id: 15,
        image: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=500&h=500&fit=crop&crop=center",
        title: "Stress management",
        duration: "1",
        unit: "hour/week",
        description: "Engaging in hobbies and creative expression fosters relaxation and self-reflection.",
    },
];
